version: '2'
services:
  tensorflow-serving:
    image: 'bitnami/tensorflow-serving:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - 9000:9000
    volumes:
      - 'tensorflow_serving_data:/bitnami'
      - '/tmp/model-data:/bitnami/model-data'
  tensorflow-inception:
    image: 'bitnami/tensorflow-inception:0'
    depends_on:
      - tensorflow-serving
    volumes:
      - 'tensorflow_inception_data:/bitnami'
      - '/tmp/model-data:/bitnami/model-data'
volumes:
  tensorflow_serving_data:
    driver: local
  tensorflow_inception_data:
    driver: local
